spring:
  application:
   name: testactuator
management:
  endpoints:
    access:
      default: NONE
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      access: READ_ONLY
  cors:
    allowed-origins: "*"
    allowed-methods: GET