spring:
  application:
   name: testactuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  cors:
    allowed-origins: "*"
    allowed-methods: GET